export const additionalCurrencies = [
  { Name: "Bitcoin", Symbol: "BTC-USD" },
  { Name: "Etherium", Symbol: "ETH-USD" },
  { Name: "Solana", Symbol: "SOL-USD" },
  { Name: "XRP", Symbol: "XRP-USD" },
  { Name: "Dogecoin", Symbol: "DOGE-USD" },
  { Name: "Cardano", Symbol: "ADA-USD" },
  { Name: "Polkadot", Symbol: "DOT-USD" },
  { Name: "Polygon", Symbol: "MATIC-USD" },
  { Name: "Litecoin", Symbol: "LTC-USD" },
  { Name: "Shiba Inu", Symbol: "SHIB-USD" },
  { Name: "Avalanche", Symbol: "AVAX-USD" },
  { Name: "Uniswap", Symbol: "UNI-USD" },
  { Name: "Chainlink", Symbol: "LINK-USD" },
  { Name: "Cosmos", Symbol: "ATOM-USD" },
  { Name: "Stellar", Symbol: "XLM-USD" },
  { Name: "Bitcoin Cash", Symbol: "BCH-USD" },
  { Name: "Internet Computer", Symbol: "ICP-USD" },
  { Name: "Filecoin", Symbol: "FIL-USD" },
  { Name: "Hedera", Symbol: "HBAR-USD" },
  { Name: "Cronos", Symbol: "CRO-USD" },
  { Name: "VeChain", Symbol: "VET-USD" },
  { Name: "NEAR Protocol", Symbol: "NEAR-USD" },
  { Name: "Algorand", Symbol: "ALGO-USD" },
  { Name: "The Graph", Symbol: "GRT-USD" },
  { Name: "Frax", Symbol: "FRAX-USD" },
  { Name: "Decentraland", Symbol: "MANA-USD" },
  { Name: "Aave", Symbol: "AAVE-USD" },
  { Name: "EOS", Symbol: "EOS-USD" },
  { Name: "Flow", Symbol: "FLOW-USD" },
  { Name: "Tezos", Symbol: "XTZ-USD" },
  { Name: "Elrond", Symbol: "EGLD-USD" },
  { Name: "Chiliz", Symbol: "CHZ-USD" },
  { Name: "Zcash", Symbol: "ZEC-USD" },
  { Name: "Basic Attention Token", Symbol: "BAT-USD" },
  { Name: "Synthetix", Symbol: "SNX-USD" },
];

export const cummulationOptions = [
  { Name: "0.01", Symbol: "0.01" },
  { Name: "0.05", Symbol: "0.05" },
  { Name: "0.1", Symbol: "0.1" },
  { Name: "1", Symbol: "1" },
  { Name: "10", Symbol: "10" },
];
